### ISSUE TITLE
Simssa DB Staging 504 Error

### ISSUE THREAD

**Issue by malajvan** [DDMAL/docker-simssadb#22]
Currently, simssadb staging is set up in the Operations repo. All nginx and ansible configs are checked to be identical to simssadb production. However, db.staging.simssa.ca shows a `504 Gateway Time-out` every time, while production works as expected
After some digging we see that the signal is coming into staging edge (jumpbox) correctly, and the connection times out happens when nginx tries to talk to the simssadb staging server. 

Here's a list of things I've tried:
- Setting Up a Blank Django Project to bring up a empty django page at different ports
- Configuring ALLOWED_HOSTS in django settings.py
- Check Firewall and ports on staging server
- Check setups between prod_edge and staging_edge
- Compare server networking and deployment setup between staging and production 
- Hard reboot the staging instance

Would really appreciate if anyone can suggest some other things we can look into

**Comment by dchiller** [comment]
> After some digging we see that the signal is coming into staging edge (jumpbox) correctly, and the connection times out happens when nginx tries to talk to the simssadb staging server.

Does this mean there is nothing in the nginx logs on the simssadb staging server?

**Comment by malajvan** [comment]
More on what I tried:
- `curl http://[simssadb staging ip]:1337` from inside simssadb staging server itself:
This works, the curl returns the right content from the django startup page
--> Means that this must be a network config or reverse proxy problem
I'm taking a second look at all of the nginx configs

**Comment by malajvan** [comment]
@kqct fixed this with changing the security group of the container
